apiVersion: v1
kind: ServiceAccount
metadata:
  name: app1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        #vault.hashicorp.com/namespace: "admin"
        vault.hashicorp.com/role: "app1"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-inject-secret-app1-config.txt: "secret/data/app1/config"
        vault.hashicorp.com/agent-inject-template-app1-config.txt: |
          {{- with secret "secret/data/app1/config" -}}
          postgresql://{{ .Data.data.username }}:{{ .Data.data.password }}@postgres:5432/wizard
          {{- end -}}
      labels:
        app: app1
    spec:
      serviceAccountName: app1
      containers:
        - name: app1
          image: jweissig/app:0.0.1
